"""empty message

Revision ID: 529654058f5c
Revises: 
Create Date: 2026-07-04 12:44:46.900891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529654058f5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('joined_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_member', schema=None) as batch_op:
        batch_op.drop_column('joined_at')

    # ### end Alembic commands ###
